In [6]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output.

In [7]:
from sklearn.model_selection import train_test_split


from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

#Keras
import keras as ks
from keras.models import Sequential
from keras.layers import Dense,Dropout,Flatten,Conv2D,MaxPooling2D
from keras.utils import np_utils


In [8]:
test_data=pd.read_csv("test.csv")
train_data=pd.read_csv("train.csv")
sample_data=pd.read_csv("sample_submission.csv")

In [9]:
train_data.shape

(42000, 785)

In [10]:
test_data.shape

(28000, 784)

In [11]:
#データの切り分け
y=train_data["label"]
X=train_data.drop("label",axis=1)

In [12]:
y.shape

(42000,)

In [13]:
X.shape

(42000, 784)

In [14]:
X

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
41995       0       0       0       0       0       0       0       0       0   
41996       0       0       0       0       0       0       0       0       0   
41997       0       0       0       0       0       0       0       0       0   
41998       0       0       0       0       0       0       0       0       0   
41999       0       0       0       0       0       0       0       0       0   

       pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  \
0           0  ...         0         0         0         0         0   
1           0  ...         0         0         0         0         0   
2           0  ...         0         0         0         0         0   
3           0  ...         0         0         0         0         0   
4           0  ...         0         0         0         0         0   
...       ...  ...       ...       ...       ...       ...       ...   
41995       0  ...         0         0         0         0         0   
41996       0  ...         0         0         0         0         0   
41997       0  ...         0         0         0         0         0   
41998       0  ...         0         0         0         0         0   
41999       0  ...         0         0         0         0         0   

       pixel779  pixel780  pixel781  pixel782  pixel783  
0             0         0         0         0         0  
1             0         0         0         0         0  
2             0         0         0         0         0  
3             0         0         0         0         0  
4             0         0         0         0         0  
...         ...       ...       ...       ...       ...  
41995         0         0         0         0         0  
41996         0         0         0         0         0  
41997         0         0         0         0         0  
41998         0         0         0         0         0  
41999         0         0         0         0         0  

[42000 rows x 784 columns]

In [15]:
y

0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

In [16]:
#訓練/テストセットへ分割
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#サイズ確認
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(33600, 784)
(33600,)
(8400, 784)
(8400,)


In [17]:
#訓練データのターゲット分布
np.array(np.unique(y_train,return_counts=True)).astype(int).T

array([[   0, 3316],
       [   1, 3775],
       [   2, 3331],
       [   3, 3414],
       [   4, 3233],
       [   5, 3093],
       [   6, 3352],
       [   7, 3508],
       [   8, 3228],
       [   9, 3350]])

In [18]:
#テストデータのターゲット分布
np.array(np.unique(y_test,return_counts=True)).astype(int).T

array([[  0, 816],
       [  1, 909],
       [  2, 846],
       [  3, 937],
       [  4, 839],
       [  5, 702],
       [  6, 785],
       [  7, 893],
       [  8, 835],
       [  9, 838]])

In [19]:
#正規化
X_train=X_train.astype("float32")/255
X_test=X_test.astype("float32")/255

In [20]:
#Keras用にデータ整形
print(X_train.shape)
print(X_test.shape)

(33600, 784)
(8400, 784)


In [21]:
X_train=X_train.to_numpy()
X_test=X_test.to_numpy()

In [22]:
X_train=X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test=X_test.reshape(X_test.shape[0], 28, 28, 1)

In [23]:
#ターゲットデータをクラスベクトルに変換
y_train=np_utils.to_categorical(y_train,10)
y_test=np_utils.to_categorical(y_test,10)

print(y_train[0:5])
print(y_test[0:5])

[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [24]:
##model_3
#Sequentialモデル生成
model_3=Sequential()

#入力層兼畳み込み層追加
model_3.add(Conv2D(32, kernel_size=(3,3),
                   activation="relu",
                   input_shape=(28,28,1)))
#プール層追加
model_3.add(MaxPooling2D(pool_size=(2,2)))
#DropOut
model_3.add(Dropout(0.25))


#畳み込み層の追加
model_3.add(Conv2D(64, kernel_size=(3,3), activation="relu"))
#プール層の追加
model_3.add(MaxPooling2D(pool_size=(2,2)))
#DropOut
model_3.add(Dropout(0.25))

#畳み込み層の追加
model_3.add(Conv2D(128, kernel_size=(3,3), activation="relu"))
#プール層の追加
model_3.add(MaxPooling2D(pool_size=(2,2)))
#DropOut
model_3.add(Dropout(0.25))

#全結合層
model_3.add(Flatten())
#全結合層
model_3.add(Dense(128, activation="relu"))
#DropOut
model_3.add(Dropout(0.25))
#出力層
model_3.add(Dense(10, activation="softmax"))

#モデルコンパイル
model_3.compile(loss="categorical_crossentropy",
               optimizer="sgd",
               metrics=["accuracy"])

model_3.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
dropout_2 (Dropout)          (None, 5, 5, 64)          0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 3, 3, 128)        

In [25]:
model_3.fit(X_train,y_train,epochs=50)

Epoch 1/50
33600/33600 [==============================] - 11s 320us/step - loss: 1.8140 - accuracy: 0.3768
Epoch 2/50
33600/33600 [==============================] - 11s 314us/step - loss: 0.7279 - accuracy: 0.7648
Epoch 3/50
33600/33600 [==============================] - 10s 312us/step - loss: 0.4690 - accuracy: 0.8536
Epoch 4/50
33600/33600 [==============================] - 10s 312us/step - loss: 0.3681 - accuracy: 0.8845
Epoch 5/50
33600/33600 [==============================] - 10s 309us/step - loss: 0.3156 - accuracy: 0.9041
Epoch 6/50
33600/33600 [==============================] - 10s 307us/step - loss: 0.2817 - accuracy: 0.9126
Epoch 7/50
33600/33600 [==============================] - 10s 308us/step - loss: 0.2582 - accuracy: 0.9206
Epoch 8/50
33600/33600 [==============================] - 10s 304us/step - loss: 0.2313 - accuracy: 0.9290
Epoch 9/50
33600/33600 [==============================] - 10s 306us/step - loss: 0.2153 - accuracy: 0.9340
Epoch 10/50
33600/33600 [============

In [26]:
X_val=test_data
print(X_val.shape)

#テストデータの前処理
#正規化
X_val=X_val.astype("float32")/255

(28000, 784)


In [27]:
X_val=X_val.to_numpy()
X_val=X_val.reshape(X_val.shape[0], 28, 28, 1)

In [28]:
X_val.shape

(28000, 28, 28, 1)

In [29]:
#テストデータで推測結果を出力
cnn_pred=model_3.predict_classes(X_val, verbose=0)

In [30]:
cnn_pred.shape

(28000,)

In [31]:
print(cnn_pred[0])

2


In [32]:
sample_data.head()

ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0

In [33]:
submissions=pd.DataFrame({"ImageId": list(range(1,len(cnn_pred)+1)),"Label": cnn_pred})

In [34]:
submissions.to_csv("submit_2.csv", index=False, header=True)

In [35]:
submissions.shape

(28000, 2)